# path to a directory with all packages
storage: ../tmp/local-registry/storage

listen:
  - 127.0.0.1:4873

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

# TODO: Codeware plugins needs to be stored in local registry during e2e tests, but all other packages can be proxied to npmjs.
# There's a problem during e2e where public packages have localhost in lock file and install within Docker container are refused to connect.
# Is it because e2e runs inside Docker containers and Verdaccio is running on host machine?
# Is the problem inside Verdaccio configuration or Docker compose configuration?
packages:
  '@cdwr/*':
    # give all users (including non-authenticated users) full access
    # because it is a local registry
    access: $all
    publish: $all
    unpublish: $all
  'create-nx-payload':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $all
    unpublish: $all
    # proxy requests to npm registry
    proxy: npmjs

# log settings; https://verdaccio.org/docs/logger
log:
  type: stdout # [stdout, file] for 'file' add a 'path' property
  format: pretty-timestamped # [pretty, pretty-timestamped]
  level: trace # [fatal, error, warn, http, info, debug, trace]

publish:
  allow_offline: true # set offline to true to allow publish offline
