name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:
  push:
    branches:
      - master
      - 'renovate/**'
  workflow_dispatch:

jobs:
  main:
    name: Test affected
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
