name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:
  push:
    branches:
      - master
      - 'renovate/**'
  workflow_dispatch:

jobs:
  main:
    name: Test Affected
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v3

      # needed for nx affected to work when CI is running on a PR
      - run: git branch --track master origin/master

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3 --code-coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
