name: CI Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
  workflow_dispatch:

jobs:
  test-affected:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node_version }}

      - name: Test
        uses: ./.github/actions/test
        with:
          # TODO: Connect repository to codecov
          codecov-token: ''
