name: E2E matrix

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug-enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  preinstall:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - 20
          - 18
        exclude:
          - os: windows-latest
            node_version: 18

    name: Cache install (${{ matrix.os }}, node v${{ matrix.node_version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          lookup-only: true
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ matrix.node_version }}-${{ github.run_id }}

      - name: Install packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable

  e2e:
    needs: preinstall
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - 20
          - 18
        package_manager:
          - npm
          # - yarn
          # - pnpm
        project:
          - nx-payload-e2e
        include:
          # os short names
          - os: ubuntu-latest
            os_name: 'Linux'
          - os: windows-latest
            os_name: 'Windows'
          # test timeouts
          - os: ubuntu-latest
            os_timeout: 60
          - os: windows-latest
            os_timeout: 60
          # configurations
          - os: ubuntu-latest
            configuration: ''
          - os: windows-latest
            # will skip docker build test since node image doesn't exist running inside a windows container
            configuration: 'windows'
        exclude:
          # windows: only npm 20
          - os: windows-latest
            package_manager: yarn
          - os: windows-latest
            package_manager: pnpm
          - os: windows-latest
            node_version: 18
      fail-fast: false

    name: E2E ${{ matrix.os_name }}/${{ matrix.package_manager }}/${{ matrix.node_version }} ${{ join(matrix.project) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ matrix.node_version }}-${{ github.run_id }}

      - name: Install packages
        run: yarn install --immutable

      - name: Set starting timestamp
        id: before-e2e
        run: |
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Run e2e tests
        id: e2e-run
        run: yarn nx e2e ${{ matrix.project }} -c ${{ matrix.configuration }}
        timeout-minutes: ${{ matrix.os_timeout }}
        env:
          NX_CACHE_DIRECTORY: 'tmp'
          NX_PERF_LOGGING: 'false'
          NX_NO_CLOUD: ${{ contains(github.head_ref || github.ref_name, 'renovate') }}
          # NX_DAEMON defaults to 'true' unless explicitly set to 'false'
          NX_DAEMON: ${{ env.NX_DAEMON == 'false' && 'false' || 'true' }}
          # NX_VERBOSE_LOGGING defaults to 'false' unless explicitly set to 'true'
          NX_VERBOSE_LOGGING: ${{ env.NX_VERBOSE_LOGGING == 'true' && 'true' || 'false' }}
          E2E_PACKAGE_MANAGER: ${{ env.E2E_PACKAGE_MANAGER }}

      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug-enabled && failure() }}
        uses: mxschmitt/action-tmate@v3.18
        timeout-minutes: 15
        env:
          # disable sudo for windows debugging
          sudo: ${{ matrix.os != 'windows-latest' }}
        with:
          sudo: ${{ env.sudo }}
