name: Nx migrate

on:
  workflow_dispatch:
  schedule:
    # Every day at 6am UTC
    - cron: '0 6 * * *'

jobs:
  nx-migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_SEMVER_TOKEN }}
          fetch-depth: 0

      - name: Set git metadata
        run: |
          git config user.name "${{ vars.SEMVER_COMMIT_NAME }}"
          git config user.email "${{ vars.SEMVER_COMMIT_EMAIL }}"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --immutable
        shell: bash

      - name: Check if @nx/workspace is outdated
        id: nx-workspace-outdated
        run: |
          IS_OUTDATED=$(test ! -z "$(npm outdated @nx/workspace)" && echo true || echo false)
          echo $IS_OUTDATED
          echo "outdated=$IS_OUTDATED" >> $GITHUB_OUTPUT

      - name: Update @nx/workspace
        if: steps.nx-workspace-outdated.outputs.outdated == 'true'
        run: yarn nx migrate latest

      - name: Install dependencies
        if: steps.nx-workspace-outdated.outputs.outdated == 'true'
        run: yarn install --no-immutable

      - name: Check if has migrations
        id: nx-workspace-has-migrations
        run: |
          HAS_MIGRATIONS=$(test -f migrations.json && echo true || echo false)
          echo $HAS_MIGRATIONS
          echo "has_migrations=$HAS_MIGRATIONS" >> $GITHUB_OUTPUT

      - name: Run @nx/workspace migrations
        if: steps.nx-workspace-has-migrations.outputs.has_migrations == 'true'
        run: yarn nx migrate --run-migrations

      - name: Test
        id: test
        if: steps.nx-workspace-outdated.outputs.outdated == 'true'
        continue-on-error: true
        uses: ./.github/actions/test
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

      - name: Commit changes
        if: steps.nx-workspace-outdated.outputs.outdated == 'true'
        run: |
          LAST_VERSION=$(npm view @nx/workspace version)
          git add .
          [[ $(git status --porcelain) ]] && git commit -m "build: 📦 update nx workspace to ${LAST_VERSION}" || echo "nothing to commit"

      - name: Remove migrations.json & commit
        if: steps.nx-workspace-has-migrations.outputs.has_migrations == 'true'
        run: |
          git rm -f migrations.json
          git commit -m "build: 📦 remove migrations.json"

      - name: Push changes
        if: steps.nx-workspace-outdated.outputs.outdated == 'true' && steps.test.outcome == 'success'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true

      - name: Create PR
        if: steps.nx-workspace-outdated.outputs.outdated == 'true' && steps.test.outcome != 'success'
        run: |
          LAST_VERSION=$(npm view @nx/workspace version)
          BRANCH="update-nx-workspace-${LAST_VERSION}"
          git checkout -b ${BRANCH}
          git push -f --set-upstream origin ${BRANCH}
          gh pr view ${BRANCH} || gh pr create -t "Update @nx/workspace to ${BRANCH}" -b "Update @nx/workspace dependencies to ${LAST_VERSION}."
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMVER_TOKEN }}
