name: Release

# There's no value in releasing on every commit,
# so this process is better handled manually when needed.
on:
  workflow_dispatch:
    inputs:
      package:
        description: Release a specific package or all packages
        required: false
        type: choice
        options:
          - all
          - create-nx-payload
          - nx-payload
          - workspace
        default: all

      release-type:
        description: Specify what kind of release to create
        required: false
        type: choice
        options:
          - auto
          - prerelease
          - premajor
          - minor
          - major
        default: auto

      empty-release:
        description: Force a patch increment even if library source didn't change?
        required: false
        type: boolean
        default: false

env:
  node_version: 18

jobs:
  test:
    runs-on: ubuntu-latest

    if: github.ref_name == 'master'

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.node_version }}

      - name: Test
        uses: ./.github/actions/test

  release:
    runs-on: ubuntu-latest

    needs: [test]

    concurrency:
      group: ${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          git-token: ${{ secrets.GH_SEMVER_TOKEN }}
          node-version: ${{ env.node_version }}
          commit-user-name: ${{ vars.SEMVER_COMMIT_NAME }}
          commit-user-email: ${{ vars.SEMVER_COMMIT_EMAIL }}

      # Use `npx` instead of `yarn` because `yarn` sets NPM_* environment variables (like NPM_CONFIG_REGISTRY).
      # This affects `npm publish` ignoring the .npmrc file, which is set up by `setup-node` action.
      # Run for all version projects and let semver decide whether to create a new release for each project.
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          configuration="${{ inputs.release-type != 'auto' && inputs.release-type || '' }}"
          projects="${{ inputs.package != 'all' && inputs.package || '' }}"
          npx nx run-many --target=version-publish --configuration=$configuration --projects=$projects --parallel=1 --nxBail=true --baseBranch=${{ github.ref_name }} --allowEmptyRelease=${{ inputs.empty-release }}
